### ISSUE TITLE
Users should permanently have the option to choose between types of updates in Software Center

### ISSUE THREAD

**Issue by Nycticorax** [getsolus/solus-sc#14]
As of this issue, Solus SC distinguishes between individual package updates candidates and sort them under the `Required`, `Security` and `Other` types. The distinction + categorization (which I will consider as one single thing for the purpose of this issue) is helpful as it allows users to maintain granular control over update candidate packages. It is an intuitive distinction too -- drawn by the vast majority of both Unix-like and non-Unix-like operating systems, regardless of their update philosophy (rolling vs non-rolling release).

Removing the distinction from Solus SC runs the risk of making updates unappealing to users who wish to maintain granular control over their packages, as they would have to find less-user-friendly ways of updating their Solus installment than those provided by the SC -- defeating the purpose of a user-friendly SC.

More generally, users who don't care one way or another would still have to upgrade in an all-or-nothing way, which runs the risk of eating up hard drive space even in cases where that is not strictly required for their installment to get the latest version of Solus (including kernel + desktop environments). This might turn out problematic as, plausibly:
- many users install Solus alongside other operating systems, especially on laptops used for both home and work;
- many users install non-system-required packages, meaning that erasing the distinction between Required / Security / Others would have users update indefinitely many packages an indefinite amount of times, when that would otherwise not be needed or wanted.

The argument in favour of granular control have here and there been opposed the claim that Solus OS version number does not represent any specific state of the OS, being used just as a tag to single out a specific subset of system-required update candidates. But this claim is not relevant for the usefulness of the distinction between Required / Security / Others -- after all, the distinction is already in force. Moreover, the distinction, and the associated option to provide users selective upgrades, make sense insofar as the version number represents **system-required** vs. **non-system-required** update candidates -- which it does. Whether the changes these update candidates encode correlate with a specific and workable state of the OS is of no relevance.

**Comment by hyphenrf** [comment]
Ahaha gosh I was just writing a forum post (felt it'd be more suitable there).
But man, you definitely hold a strong argument than I wrote. I'll reference it in the post!

I'd like to add just one thing if you let me. Although disk space can be arguable, metered connections is very real. I would definitely like to keep my system secure (with security upgrades) while keeping non-essential packages for when I'm not paying lots of money per megabyte (i.e. when travelling). This is one-of-many legitimate use-cases to such distinction.

**Comment by Nycticorax** [comment]
> I'd like to add just one thing if you let me. Although disk space can be arguable, metered connections is very real. I would definitely like to keep my system secure (with security upgrades) while keeping non-essential packages for when I'm not paying lots of money per megabyte (i.e. when travelling). This is one-of-many legitimate use-cases to such distinction.
Very true indeed!

**Comment by hyphenrf** [comment]
It's a shame that the discussion on was closed https://discuss.getsol.us/d/859-future-plans-for-software-center when the exchange of opinions wasn't over, and when the reason to closing it seems to be ending a side-discussion that derailed from the focal point anyway.

I'm gonna place my reply here just for future reference anyway.

replying to @kyrios#7560's last comment:
This may be disappointing but nothing broke so far!
I'm using my personal experiences as non-inclusive examples but they're not really what starting this discussion is aiming to argue for. If it was just MY case, I'd go on my way happily knowing exclusion will still be a thing in eopkg (my preferred way to handle packages anyway) and write an alias in my .bash_aliases file for updating things with exclusion. Solved.
And Josh did mention that exclusion is definitely staying.

But the real argument here is more of a conceptual one. Where do you draw the line between "sane defaults" versus "enforced behaviour"?

Please. Correct me if I'm wrong, but the kernel is one of the _safer_ things to hold. Being such a versatile program with a billion unique use-cases, it is designed to work on different combinations of different systems. It also makes sense that whatever relies on it will surely take into account backwards compatibility to a whole major version number, not just a few minor recent ones.
I do follow CVE databases for vulns and do read the changelogs of the packages I hold just in case something important arises, but the kernel I currently have serves me well. The new update doesn't introduce anything relevant to my system that I missed when 4.20.16 was the most recent version, and no major security issues that can realistically harm me in my personal computing use case. This is part of my own responsibility when I opted to hold this package. And of for some reason my system was still attacked/broken, it's also my own responsibility for deviating from the defaults.

I completely understand that what I'm doing is bound to introduce instability. And I did mention earlier in the discussion, if you read it, that I'm all with the figurative 'NO WARRANTY' big red button to let users know that what they're opting in for would leave only themselves to blame if anything breaks, not the devs. While at the same time keeps inexperienced users away from those options. Give me the knife and let me use it at my own judgement and risk assessment, don't give me a spork when I want to cut an apple, just because a knife is too dangerous.



Replying to @Harvey#7580's most recent comment: 
I thought this forum was all about discussing things as equals (You, I–nameless guy, and Kyrios) and sharing knowledge. Not taking maintainers' words as bible and chanting them in caps lol.

It's true that you could argue, by sheer number of incremental updates, that rolling distros are more vulnerable to holding side-effects than fixed-point ones. It's not the focal point of my argument, really. Not once have I denied the stability trade-off. It's never been my concern here. Apparently I can't stress this enough; **I am arguing for enabling users to have options that can potentially cause instability**. And Nycticroax was correct on that.
And although this form of argument isn't one I favour, but for your sake, just look at the toolings of many rolling distros; Debian Sid, Alpine, Tumbleweed, Arch and derivatives, Void, etc.. They all have their solutions to holding packages. If it really was just harmful for a rolling release model, and not just a stability shaker in general, One would think those distros would be first to deprive the users from those so-claimed system-nuking options.

In reality, defaults are always going to be the most stable way to do things, but enforcing defaults by depriving users of the means to make their system their own seems just wrong. My reasons could be silly. Yeah I like a version number. But don't confuse them for uninformed. And don't take them as the exclusive reasons of this discussion.



Replying to Josh's most recent comment:

I did opt for rolling because in most cases I do want the latest. It's just not always the case. And not for all packages. And I'm not the only user of this OS. Not all-or-nothing. I find the all-or-nothing argument really harmful.

Asking you to ensure the reliability/stability/debugging of non-default non-supported builds is definitely asking way too much. And I'm all with you on meeting it with refusal. It's not anyone's job but the one who decided to hack away in the system.

An example was layed for windows updates. Windows lets you update the end-user _programs_ as you please. I don't think holding back Libreoffice will break the system. It may only break Libreoffice and that's a minor inconvenience at best. One of the first things you ask for before offering bug support is "are you on the latest release of xyz" anyway. 
I've read suggestions on the solus bug tracker that further dividing packages may be the better option. Doing so will let maintainers enforce essential upgrades while keeping updating system-secondary programs like LibreOffice and GIMP something the user chooses.

I understand that the current way of selecting packages can be harmful for "average users", and that there is no way for them to really tell. But at the same time, offering again putting this option in an experimental/unstable/advanced/here-be-dragons/name-it-as-you-wish-options menu. Instead of completely getting rid of it.

Wouldn't part of user-friendliness be to put different levels of option and customization abstractions for different levels of users?

**Comment by JoshStrobl** [comment]
See my comments at https://discuss.getsol.us/d/859-future-plans-for-software-center/28
